CROSS_COMPILE ?=
GCC=$(CROSS_COMPILE)gcc

micsend:mic.o
	$(GCC) -o micsend mic.o -lpthread -I$(PWD)/../../libavcodec/install_sdk/x86/include/ \
    -L$(PWD)/../../libavcodec/install_sdk/x86/lib/ -lSKP_SILK_SDK -lm  -lspeex -lspeexdsp -lm -lasound

	cp micsend /tftpboot
	
mic.o:mic.c config.h
	$(GCC) -c -o mic.o mic.c -I$(PWD)/../../libavcodec/install_sdk/x86/include/ \
    -L$(PWD)/../../libavcodec/install_sdk/x86/lib/

clean:
	rm -rf *.o micsend /tftpboot/micsend
